// Generated by CoffeeScript 1.6.2
(function() {
  var REFRESH_RATE, TILE_SIZE, bombs, bombs_list, canvas, context, exploded, flags_list, flipped_list, get_neighbors, height, level, levels, mouse_pos, num_colors, running, time, width, won;

  TILE_SIZE = 30;

  REFRESH_RATE = 120;

  running = false;

  exploded = false;

  won = false;

  time = level = width = height = bombs = 0;

  bombs_list = [];

  flags_list = [];

  flipped_list = [];

  mouse_pos = {};

  levels = [
    {
      x: 8,
      y: 8,
      bombs: 10
    }, {
      x: 16,
      y: 16,
      bombs: 40
    }, {
      x: 31,
      y: 16,
      bombs: 99
    }
  ];

  num_colors = ["#0000FF", "#008040", "#FF0000", "#000080", "#800040", "#408080", "#000000", "#808080"];

  /*
  # Drawing Functions
  */


  get_neighbors = function(x, y) {
    return [
      {
        x: x - 1,
        y: y - 1
      }, {
        x: x - 1,
        y: y
      }, {
        x: x - 1,
        y: y + 1
      }, {
        x: x,
        y: y - 1
      }, {
        x: x,
        y: y + 1
      }, {
        x: x + 1,
        y: y - 1
      }, {
        x: x + 1,
        y: y
      }, {
        x: x + 1,
        y: y + 1
      }
    ];
  };

  canvas = $("canvas")[0];

  context = canvas.getContext("2d");

}).call(this);
